version: CI Build {build} - AppVeyor

pull_requests:
  do_not_increment_build_number: false
  
branches:
  only:
  - main
  
max_jobs: 2

image:
- Visual Studio 2015

platform:
- x86

configuration:
- Release

matrix:
  fast_finish: true

artifacts:
  openspadesplus/openspades.mk/
  openspadesplus/openspadesplus/openspades.mk/ #just incase
  
build_script:
  ## git submodules ##
  - "git submodule init"
  - "git submodule update"

  ## git stuff ##
  - "git pull origin main"

  ## vcpkg ##
  - "vcpkg update"
  - "vcpkg install @vcpkg_x86-windows.txt" # TEMP - required by cmake in sdl2-image-fix-attempt
  
  ## xiph libogg error 12175 fix (TLS 1.2 not enabled in AppVeyor) ##
  - mkdir "C:\projects\openspadesplus\vcpkg\downloads\"
  - curl "https://cdn.discordapp.com/attachments/545659735903567874/1096808186134134925/ogg-v1.3.5.tar.gz" -o "C:\projects\openspadesplus\vcpkg\downloads\xiph-ogg-v1.3.5.tar.gz"

  ## attempt to fix "missing sdl2-image in path" by manually running cmake ##
  - "mkdir openspades.mk"
  - "cd openspades.mk"
  - "cmake -A Win32 -D CMAKE_BUILD_TYPE=RelWithDebInfo -D VCPKG_TARGET_TRIPLET=x86-windows-static"

  ## actual build script ##
  - ps: "./build.ps1 -OpenSpadesFlavor P -URL https://github.com/nonperforming/openspadesplus.git -DirectoryName ../OpenSpadesPlus"