version: CI Build {build} - AppVeyor

pull_requests:
  do_not_increment_build_number: false
  
branches:
  only:
  - main
  
max_jobs: 2

image:
- Visual Studio 2015

platform:
- x86

configuration:
- Release

matrix:
  fast_finish: true

artifacts:
  openspadesplus/openspades.mk/
  openspadesplus/openspadesplus/openspades.mk/ #just incase
  
build_script:
  ## git submodules ##
  - "git submodule init"
  - "git submodule update"

  ## git stuff ##
  - "git pull origin main"

  ## vcpkg ##
  - "vcpkg update"
  #- "vcpkg install freetype:x86-windows-static"
  #- "vcpkg install opusfile:x86-windows-static"
  #- "vcpkg install opus:x86-windows-static "
  #- "vcpkg install libogg:x86-windows-static"
  #- "vcpkg install sdl2:x86-windows-static"
  #- "vcpkg install libjpeg-turbo:x86-windows-static"
  #- "vcpkg install sdl2-image[libjpeg-turbo]:x86-windows-static"
  #- "vcpkg install glew:x86-windows-static"
  #- "vcpkg install curl:x86-windows-static"
  
  ## xiph libogg ##
  - mkdir "C:\projects\openspadesplus\vcpkg\downloads\"
  - curl "https://cdn.discordapp.com/attachments/545659735903567874/1096808186134134925/ogg-v1.3.5.tar.gz" -o "C:\projects\openspadesplus\vcpkg\downloads\xiph-ogg-v1.3.5.tar.gz"

  ## actual build script ##
  - ps: "./build.ps1 -OpenSpadesFlavor P -URL https://github.com/nonperforming/openspadesplus.git -DirectoryName ../OpenSpadesPlus"