version: CI Build {build} - AppVeyor

pull_requests:
  do_not_increment_build_number: false
  
branches:
  only:
  - main
  
max_jobs: 2

image:
- Visual Studio 2015

platform:
- x86

configuration:
- Release

matrix:
  fast_finish: true

artifacts:
  openspadesplus/openspades.mk/
  openspadesplus/openspadesplus/openspades.mk/ #just incase
  
build_script:
  - "git submodule init"
  - "git submodule update"
  - "vcpkg update"
  - ps: "./build.ps1 -OpenSpadesFlavor P -URL https://github.com/nonperforming/openspadesplus.git -DirectoryName ../OpenSpadesPlus"
